In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\wahiduzzaman.fahad\Downloads\AB_NYC_2019.csv")

In [3]:
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23

In [4]:
df.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
dtype: object

In [7]:
df['occupied_days'] = 365-df['availability_365']

df['revenue'] = df['price'] * df['occupied_days']

In [8]:
df

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,occupied_days,revenue
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365,0,0
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355,10,2250
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365,0,0
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194,171,15219
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0,365,29200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48890,36484665,Charming one bedroom - newly renovated rowhouse,8232441,Sabrina,Brooklyn,Bedford-Stuyvesant,40.67853,-73.94995,Private room,70,2,0,NaN,NaN,2,9,356,24920
48891,36485057,Affordable room in Bushwick/East Williamsburg,6570630,Marisol,Brooklyn,Bushwick,40.70184,-73.93317,Private room,40,4,0,NaN,NaN,2,36,329,13160
48892,36485431,Sunny Studio at Historical Neighborhood,23492952,Ilgar & Aysel,Manhattan,Harlem,40.81475,-73.94867,Entire home/apt,115,10,0,NaN,NaN,1,27,338,38870
48893,36485609,43rd St. Time Square-cozy single bed,30985759,Taz,Manhattan,Hell's Kitchen,40.75751,-73.99112,Shared room,55,1,0,NaN,NaN,6,2,363,19965
48894,36487245,Trendy duplex in the very heart of Hell's Kitchen,68119814,Christophe,Manhattan,Hell's Kitchen,40.76404,-73.98933,Private room,90,7,0,NaN,NaN,1,23,342,30780

In [10]:
df.groupby('room_type')[['revenue']].sum()

                    revenue
room_type
Entire home/apt  1256326208
Private room      482356493
Shared room        18236007

In [16]:
df.groupby(['neighbourhood','room_type'])[['revenue']].sum().sort_values('revenue', ascending=False)

                                    revenue
neighbourhood    room_type
Williamsburg     Entire home/apt  102569295
Upper West Side  Entire home/apt   81404235
East Village     Entire home/apt   71345488
Upper East Side  Entire home/apt   66767393
Hell's Kitchen   Entire home/apt   62622889
...                                     ...
Tottenville      Private room           110
South Ozone Park Shared room              0
Hollis           Shared room              0
Fort Wadsworth   Entire home/apt          0
Bellerose        Shared room              0

[540 rows x 1 columns]

In [13]:
df.groupby(['neighbourhood','room_type'])['revenue'].sum().sort_values()

neighbourhood     room_type
Hollis            Shared room                0
Fort Wadsworth    Entire home/apt            0
Bellerose         Shared room                0
South Ozone Park  Shared room                0
Tottenville       Private room             110
                                       ...
Hell's Kitchen    Entire home/apt     62622889
Upper East Side   Entire home/apt     66767393
East Village      Entire home/apt     71345488
Upper West Side   Entire home/apt     81404235
Williamsburg      Entire home/apt    102569295
Name: revenue, Length: 540, dtype: int64

In [11]:
df.groupby('room_type')[['price']].mean()

                      price
room_type
Entire home/apt  211.794246
Private room      89.780973
Shared room       70.127586

In [18]:
df.dtypes

id                                  int64
name                               object
host_id                             int64
host_name                          object
neighbourhood_group                object
neighbourhood                      object
latitude                          float64
longitude                         float64
room_type                          object
price                               int64
minimum_nights                      int64
number_of_reviews                   int64
last_review                        object
reviews_per_month                 float64
calculated_host_listings_count      int64
availability_365                    int64
occupied_days                       int64
revenue                             int64
dtype: object

In [20]:
df['last_review'] = pd.to_datetime(df['last_review'], errors='coerce')

In [21]:
df['last_review'].dt.day_name()

0         Friday
1        Tuesday
2            NaN
3         Friday
4         Monday
          ...
48890        NaN
48891        NaN
48892        NaN
48893        NaN
48894        NaN
Name: last_review, Length: 48895, dtype: object

In [23]:
df.groupby(df['last_review'].dt.day_name())[['revenue']].sum()

               revenue
last_review
Friday       150052682
Monday       243292014
Saturday     182954324
Sunday       313570374
Thursday     119615516
Tuesday      161012182
Wednesday    134636522